import React from 'react';
import {HashLink as Link} from 'react-router-hash-link';

function Default() {
    return (
        <>
        <p>
        IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
        IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
            IOFJEZIOFIOEJZIOFJZEIFJEZIOFJIZEJFIEZIJFOIPGHIOREGIOUHERUG
        </p>
        </>
            
        
    );
}

export default Default;